### PR TITLE
Babel 6.x support

### LINKED ISSUE #4: Babel 6.x support
- [Babel 6.0.0 Released](http://babeljs.io/blog/2015/10/29/6.0.0/)

> Plugin API
We received a lot of feedback that the plugin API was confusing, so in Babel 6, it’s a bit simpler. Note that this is a breaking change, but it should reduce confusion quite a bit.

> Plugin Authors: 
When updating your plugins, please remember to bump your major versions since this make Babel 5 and 6 incompatible. Semver is important!

### PR DESCRIPTION
**Pull request by twada**
Wrestling with Babel6

- [x] update dependencies
- [x] dealing with Plugin API changes
- [x] dealing with internal SPI changes
- [x] dealing with tree node type changes
- [x] wrestling with Babel6 presets-es2015
- [x] wrestling with Babel6 presets-stage-3
- [x] make it work
- [x] back to all green
- [x] remove dirty hacks
- [x] make it right
- [x] make it fast (if possible)
- [x] README
- [x] CHANGELOG for 2.0.0
- [x] field test

fixes #4

### CODE REVIEW

**Comment by twada** [comment]
Doesn't work with babel-preset-es2015 yet since [Babel6 plugins run AFTER presets ?](https://github.com/babel/babel/issues/2688#issuecomment-152696562).

- [Presets make it impossible to plugins when order is important · Issue #2648 · babel/babel](https://github.com/babel/babel/issues/2648)
- [transforming class properties · Issue #2688 · babel/babel](https://github.com/babel/babel/issues/2688)

**Comment by twada** [comment]
[AVA is upgrading to Babel 6](https://github.com/sindresorhus/ava/issues/117).
Should not keep AVA guys waiting long.

**Comment by jamestalmage** [comment]
@twada 

Did you see this comment: https://github.com/babel/babel/issues/2648#issuecomment-152746511

You should be able to work with presets and plugins like this: 

```json
{
  "presets": [
    {
      "plugins": [
        "transform-foo",
        "transform-bar"
      ]
    },
    "es2015"
  ]
}
```

**Comment by twada** [comment]
@jamestalmage Thank you for your information. I'm still wrestling with Babel6 but war is almost over...

**Comment by twada** [comment]
@jamestalmage And of course, before merging this pull-req, I must port your great contributions in a Babel6 way.

**Comment by jamestalmage** [comment]
WOOOT!
:clap: :+1: 

// @sindresorhus

**Comment by twada** [comment]
@jamestalmage Thanks!!

**Comment by sindresorhus** [comment]
Awesome work people! :)

**Comment by twada** [comment]
@sindresorhus That was a tough one ;)
I'm looking forward to seeing AVA running with Babel6 !

**Comment by sindresorhus** [comment]
@jamestalmage is working on it in https://github.com/sindresorhus/ava/pull/212.

**Comment by twada** [comment]
Thanks @jamestalmage !

**Comment by jamestalmage** [comment]
> @jamestalmage is working on it in sindresorhus/ava#212.

as we speak!

**Pull request merged**
